Create ChoreDice.py
HDCodePractice/MakePythonProject pull request #8
Opened 2020-08-31 14:58 UTC by Sichengthebest

创造机器人

2020-09-01 02:01 UTC, hdcola reviewed
哈哈，提到这里我很开心。但是你应该提交到你自己的 MyFirstBot里，然后邀请我去看才对啊 :)

2020-09-01 02:01 UTC, hdcola commented on Sichengthebest/Work/ChoreDice.py
> +updater = Updater(token='1187785181:AAGLGNddzyqx4wY8bSRhByMAZtWlQZPBKhY', use_context=True)
看一下如何不要把自己的token放到github这一段来把你的token隐藏起来。另外，在BotFather上，把你自己的token换一个新的。

2020-09-01 02:01 UTC, hdcola commented on Sichengthebest/Work/ChoreDice.py
> +updater = Updater(token='1187785181:AAGLGNddzyqx4wY8bSRhByMAZtWlQZPBKhY', use_context=True)
看看这里 https://github.com/HDCodePractice/MakePythonProject/blob/master/%E7%AC%AC%E4%BA%8C%E8%AF%BE%20%E4%BD%BF%E7%94%A8GitHub%E5%92%8C%E5%BB%BA%E7%AB%8B%E7%AC%AC%E4%B8%80%E4%B8%AA%E6%9C%BA%E5%99%A8%E4%BA%BA.md#%E6%B3%A8%E6%84%8F

2020-09-01 16:47 UTC, hdcola requested changes

2020-09-01 16:47 UTC, hdcola commented on Sichengthebest/Work/ChoreDice.py
> +echo_handler = MessageHandler(Filters.text & (~Filters.command), echo)
如果有了扔骰子，这个echo就不能有了呀，因为这个就不好放到群里去了吧。 :)

2020-09-03 14:31 UTC, Sichengthebest commented on Sichengthebest/Work/ChoreDice.py
> +updater = Updater(token='1187785181:AAGLGNddzyqx4wY8bSRhByMAZtWlQZPBKhY', use_context=True)
ok
close?

2021-03-13 16:08 UTC, closed without merging